# Generated by Django 5.0.2 on 2025-08-25 12:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('c_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='user',
            table='c_users',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='c_user_profiles',
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, max_length=150, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_contacts', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'c_user_contacts',
                'ordering': ['display_name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='contacts',
            field=models.ManyToManyField(related_name='related_to', through='c_accounts.Contact', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='idx_user_username'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='idx_user_email'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['owner'], name='idx_contact_owner'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['contact_user'], name='idx_contact_user'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['display_name'], name='idx_contact_display_name'),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('owner', 'contact_user')},
        ),
    ]
